version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_HOST=localhost
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345asdf
            - POSTGRES_DB=simple_blog_api
    api:
        depends_on:
            - postgres
        #build:
           #dockerfile: Dockerfile
           #dockerfile: Dockerfile.dev
           #context: .
        image: gk4161/simple-api:latest
        ports:
            - "3000:3000"       
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345asdf
            - POSTGRES_DB=simple_blog_api
         